version: '3.8'

services:
  leetcode_backend:
    env_file:
      - .env
    build:
      context: ./backend
      args:
        MONGODB_URI:
        TEST_MONGODB_URI:
    ports:
      - 3001:3001
      - 3000:3000
    container_name: leetcode_backend
    restart: always
    stdin_open: true
    tty: true
  leetcode_frontend:
    depends_on:
      - leetcode_backend
    environment:
        - DANGEROUSLY_DISABLE_HOST_CHECK=true
    build:
      context: ./frontend
    container_name: leetcode_frontend
    network_mode: service:leetcode_backend
    restart: always
    stdin_open: true
    tty: true
  nginx:
    image: nginx:stable
    restart: on-failure
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on: [leetcode_backend, leetcode_frontend]