version: '3.8'

services:
  leetcode_backend:
    env_file:
      - .env
    build:
      context: ./backend
      args:
        MONGODB_URI:
        TEST_MONGODB_URI:
    ports:
      - 3001:3001
      - 3000:3000
    container_name: leetcode_backend
    restart: always
    stdin_open: true
    tty: true
  leetcode_frontend:
    depends_on:
      - leetcode_backend
    environment:
        - DANGEROUSLY_DISABLE_HOST_CHECK=true
    build:
      context: ./frontend
    container_name: leetcode_frontend
    network_mode: service:leetcode_backend
    restart: always
    stdin_open: true
    tty: true
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    container_name: reverse-proxy
    depends_on: [leetcode_backend, leetcode_frontend]
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
