name: Regular
on:
  pull_request:
  push: { branches: [main] }
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
  
jobs:
  regular:
    name: cron job for updating leetcode questions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: npm install in backend
      working-directory: ./backend
      run: npm install
    - name: run cron job
      working-directory: ./backend
      run: node insertData.js
  
