name: Regular
on:
  pull_request:
  push: { branches: [main, testing] }
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:
  
jobs:
  regular:
    name: cron job for updating leetcode questions
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: create env file
      run: |
        touch .env
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
        echo TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        cat .env
        pwd
        ls -a
    - name: npm install in backend
      working-directory: ./backend
      run: npm install
    - name: run cron job
      working-directory: ./backend
      run: node insertData.js
  
